lib/dfe/reference_data/qualifications.rb
It would be useful to have this so we can easily find the foundation degrees for the Apply degree dropdown autocomplete
=> Add foundation

lib/dfe/reference_data/degrees.rb
This is a common combined degree subject which has been entered 199 times as a UK degree subject.
=> Add subject: English language and literature

spec/lib/dfe/reference_data/degrees/single_subjects_spec.rb
This just tries to catch us from making mistakes...
=> Add some basic tests for single subjects

docs/lists_degrees.md, lib/dfe/reference_data/degrees/types.rb
Talking with Rob, I don't think these are DQT ids. They're actually DTTP ids that are misnamed.
=> Rename attribute degree type attribute from dqt_id to dttp_id

lib/dfe/reference_data/degrees/types.rb
Adding some more match synonyms.
We're moving over to this repo, and have historic values that include `Hons` in various styles - this adds them so they match correctly.
=> Add further match synonyms matching on hons

lib/dfe/reference_data/degrees/institutions.rb
We had an example of an Apply user with institution of "RGU Aberdeen"
=> Add synonym

README.md, docs/decisions/0002-embedded-schemas.md, docs/ruby.md, docs/schema.md, lib/dfe/reference_data/degrees.rb, lib/dfe/reference_data/degrees/grades.rb, lib/dfe/reference_data/degrees/institutions.rb, lib/dfe/reference_data/degrees/subjects.rb, lib/dfe/reference_data/degrees/types.rb, lib/dfe/reference_data/demo.rb, lib/dfe/reference_data/hardcoded_reference_list.rb, lib/dfe/reference_data/joined_reference_list.rb, lib/dfe/reference_data/qualifications.rb, lib/dfe/reference_data/reference_list.rb, lib/dfe/reference_data/tweaked_reference_list.rb, spec/gem_helper.rb, spec/lib/dfe/reference_data/degrees/grades_spec.rb, spec/lib/dfe/reference_data/degrees/institutions_spec.rb, spec/lib/dfe/reference_data/degrees/subjects_spec.rb, spec/lib/dfe/reference_data/degrees/types_spec.rb, spec/lib/dfe/reference_data/qualifications_spec.rb, spec/support/schema_validation.rb
This is just the schema component of https://github.com/DFE-Digital/dfe-reference-data/pull/46
It comprises:
- A schema notation for reference data lists
- Documentation thereof
- Validation code to check that the hardcoded lists match their schemas (run from rspec so we find mistakes easily)
- Fixes to lists where I found errors when adding schemas to them!
=> Schema validation

docs/lists_degrees.md, lib/dfe/reference_data/degrees/institutions.rb, spec/lib/dfe/reference_data/degrees/institutions_spec.rb
- Added `GENERIC_INSTUTITIONS`
- Added `INSTITUTIONS_INCLUDING_GENERICS`, a combination of `GENERIC_INSTUTITIONS` and `INSTITUTIONS`
=> Added generic institution choices

Rakefile, lib/dfe/reference_data/degrees/types.rb
Adds a new type in preparation for a new option HESA are adding. This was likely a missing one as they had BA but not BSc.
=> Add new degree type

CHANGELOG.md, Rakefile, docs/lists_degrees.md, lib/dfe/reference_data/degrees/types.rb, lib/dfe/reference_data/joined_reference_list.rb, lib/dfe/reference_data/reference_list.rb, spec/lib/dfe/reference_data/degrees/types_including_generics.rb, spec/lib/dfe/reference_data/degrees/types_spec.rb, spec/lib/dfe/reference_data/joined_reference_list_spec.rb
As per https://trello.com/c/ELGllTxj/603-add-unknown-option-to-degree-types
=> "Not available" code for degree types

docs/lists_itt.md, lib/dfe/reference_data/itt/incentives.rb, lib/dfe/reference_data/itt/subjects.rb, spec/lib/dfe/reference_data/itt/subjects_spec.rb
As per https://trello.com/c/T4xP8tVb/791-add-incentives-for-2021-2022-cycle-in-dfereferencedata
=> Added ITT subject incentives for 2020-2021, 2021-2022, and 2023-2024

CHANGELOG.md, docs/lists_degrees.md, lib/dfe/reference_data/degrees/grades.rb
This is a request from analytics folks who want to display degree grades, but don't want massive long names like "Upper Second Class Honours (2:1)"
=> Added abbreviations for degree grades

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
Update CHANGELOG.md to mention the closed PR of the last release (only part of release v2.3.1 was complete)
Update gem version number before deploying new release
=> release v2.3.2

lib/dfe/reference_data/degrees/institutions.rb
Update ukprn for Hult institution
=> Update ukprn for Hult

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
Changes:
Update ukprn for Hult #89
=>  release v2.3.3

lib/dfe/reference_data/itt/subjects.rb
Clarification of notes in code - Classical Greek Studies is a language
=> Updates notes for Classical Greek studies

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
Should have been done as part of this PR: https://github.com/DFE-Digital/dfe-reference-data/pull/97
=> Update Version to 3.1.0

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/age_ranges.rb, lib/dfe/reference_data/version.rb
https://trello.com/c/Atp2CAJz
Related to https://github.com/DFE-Digital/dfe-reference-data/pull/97
Added a missing constant to age_ranges.rb
=> Add UPPER_BOUND_PRIMARY_AGE to Age Ranges

lib/dfe/reference_data/itt/incentives.rb, lib/dfe/reference_data/itt/subjects.rb, spec/lib/dfe/reference_data/itt/incentives_spec.rb
[Trello ticket](https://trello.com/c/8CFzsN0i/1549-create-new-incentives-reference-table)
These updates to the incentives table are so that it has a better format that is easier for legibility and maintaining.
The changes include:
1. Removing the 'name' column and renaming this as a 'note'
2. Adding a 'subject_name' - the name of the subject associated with the incentive
3. Adding itt_categories_id - the unique identifier for this ITT subject
4. Separating out the incentive so that it applies per subject
5. Adding an academic cycle - the last four digits of the end of the academic cycle
=> Update incentives table

CHANGELOG.md
Update CHANGELOG.md to v3.2.0 changes -
Update incentives table #101
Update rake task to add minor versions #102
=> release v3.2.0

CHANGELOG.md
=> Update Changelog for 3.3.0

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
**Merged pull requests:**
- Add codes to disability hesa [\#108](https://github.com/DFE-Digital/dfe-reference-data/pull/108)
- Allow data to be sent to new Big Query project [\#106](https://github.com/DFE-Digital/dfe-reference-data/pull/106)
=> Release 3.4.0

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
Add 2025-2026 cycle dates [\#114](https://github.com/DFE-Digital/dfe-reference-data/pull/114)
=> release v3.5.1

lib/dfe/reference_data/itt/cycles.rb
=> Update find_opens date

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
- Add converter.rb and update Rakefile [\#113](https://github.com/DFE-Digital/dfe-reference-data/pull/113)
=> Release v3.6.0

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
Getting artifact to upload to github
=> Release v3.6.2

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
Update package for 2025-2026 #117 [\#117](https://github.com/DFE-Digital/dfe-reference-data/pull/117)
=> Release PR

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .rubocop.yml, README.md, Rakefile, bin/import_cah_mappings, dfe-reference-data.gemspec, lib/dfe/reference_data/bigquery/importer.rb, lib/dfe/reference_data/hardcoded_reference_list.rb, lib/dfe/reference_data/helpers/sqlite_conversion_helper.rb, lib/dfe/reference_data/itt/cycles.rb, lib/dfe/reference_data/joined_reference_list.rb, lib/dfe/reference_data/tweaked_reference_list.rb, spec/lib/dfe/reference_data/bigquery/converter_spec.rb
This PR does  the following:
Update ruby version to 3
Automate the changelog generator
Create a release sqlite artifact instead of a workflow artifact
Update the readme release instructions
=> Release a Sql artifact

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/itt/subjects.rb, lib/dfe/reference_data/version.rb
When updating the incentives data for the latest cycle the question arose whether graphic design should be associated with a D&T (design and technology) incentive or A&D (art and design) - this PR associates it with D&T
=> update graphic design
