DFE-Digital/dfe-reference-data

lib/dfe/reference_data/degrees.rb
Reviewing usage of our new degree flow, someone had typed in `BASocSc`, an abbreviation for Bachelor of Social Science.
We already have a "Bachelor of Social Science" degree type, but the abbreviation was BSS. According to Wikipedia, [both are used](https://en.wikipedia.org/wiki/Bachelor_of_Social_Science) worldwide. 
I did some quick Googling, and found that the University of Manchester currently award a BASocSc: [BSocSc Sociology](https://www.manchester.ac.uk/study/undergraduate/courses/2022/00678/bsocsc-sociology/). All other undergraduate social sciences degrees seem to award BA or BSc. I could find no course offering a degree with a BSS abbreviation. No candidate has previously entered BSS as their degree type either.
I've added BSS as a synonym just in case.
=> Change abbreviation BSS to BASocSc

lib/dfe/reference_data/degrees.rb
Henley Business School is now part of the University of Reading, but used to be independent and has its own identity:
* https://www.henley.ac.uk
* https://en.wikipedia.org/wiki/Henley_Business_School
=> Add suggestion synonym: Henley Business School

README.md
Noticed a small typo in the README whilst we were setting this up in Register - method should be `all_as_hash'
=> Correct small typo on `all_as_hash`

lib/dfe/reference_data/degrees.rb
These seem to be synonyms, with some universities using 'Classics' and others using 'Classical Studies'.
The UCAS subject guide uses both terms: https://www.ucas.com/explore/subjects/classical-studies
=> Add Classics as synonym for Classical Studies

lib/dfe/reference_data/degrees.rb
4 candidates have entered 'OTHM' as the organisation who has awarded them a degree-level qualification (Level 6 Diploma).
See https://www.othm.org.uk/default.aspx - the organisation has a UKPRN reference (10032618) and an Ofqual Recognition Number (RN5284).
=> Add organisation: OTHM Qualifications

lib/dfe/reference_data/degrees.rb
38 candidates have entered 'Computing' as their degree subject.
Whilst "Computing and information technology" is in the list, as does "Information technology", "Creative computing", "Applied computing", "Parallel computing", "Neural computing", "High performance computing", "Business computing", "Computer science", and so on... - "Computing" is not listed as a standalone subject.
Examples of undergraduate courses which use 'Computing' as degree title:
* https://www.gre.ac.uk/undergraduate-courses/ach/computing-bsc-hons
* https://www.imperial.ac.uk/study/ug/courses/computing-department/computing-beng/
* https://www.port.ac.uk/study/courses/bsc-hons-computing
The HESA code 100367 (Computing and information technology) is reused as this is likely the closest match.
=> Add Computing as a stand-alone subject

lib/dfe/reference_data/degrees/institutions.rb
I think we're safe to always convert `Open University` to `The Open University` ?
=> Make Open University a match synonym

docs/lists_degrees.md, lib/dfe/reference_data/degrees/types.rb
Adds three new master level qualifications which we saw somewhat regularly in the Apply free text data.
Note `Master in science (MSci)` is a distinct and different type from `Master of science (MSc)`.
=> Add new master level degree types

lib/dfe/reference_data/degrees/types.rb
* Rename the PhD flavour of Doctor of Philosophy to PhD
There are two entries with the name "Doctor of Philosphy". This has to be handled in client applications and can cause ambiguous select entries when displayed to users.
Given this qualification is commonly referred to as 'PhD' it seems reasonable to use that as the name to solve this problem.
=> Doctor of Philosophy -> PhD

lib/dfe/reference_data/degrees/institutions.rb
For 22/23 HESA has made a number of changes to the degree institution field.
Three of the entries we already had have now been added to [HESA in C22053](https://www.hesa.ac.uk/collection/c22053/e/degest). This updates to use the new HESA codes.
Note this does *not* add any other new items added in HESA.
=> Add new HESA codes from C22053

lib/dfe/reference_data/degrees/institutions.rb
The two being the same causes a test failure due to duplication.
=> Remove synonym that matches name exactly

lib/dfe/reference_data/degrees/institutions.rb
https://trello.com/c/9qNctNxM/4652-register-trainee-teachers
A provider cannot find the closest match, so a request has been made by support to add it to the list of institutions.
- Add `The Institute of Chartered Accountants of Scotland` to `INSTITUTIONS`
=> Add 'Institute of Chartered Accountants of Scotland' to institutions

lib/dfe/reference_data/degrees/institutions.rb
I've gone through all entries in the institution list that contain `st` or `saint` and made sure we have synonyms to cover `st`, `st.` and `saint` - so a user using any should work (or a system using these to match).
=> Add synonyms to handle abbreviations for saint

docs/lists_degrees.md
As per @steventux 's request on another PR, I've referenced the HESA field "shortnames" in the docs, where appropriate.
To clarify, we have lists that are potentially supersets of the HESA lists, so have fields with names like `hesa_itt_code` that link our list entries to the HESA lists *where there is a corresponding HESA list entry*, and don't where there isn't. 
This means that, in our documentation, the `hesa_itt_code` field is the thing that connects with the HESA list, so that's where the link to the HESA list is documented.
As our list itself doesn't necessarily correspond exactly to the HESA list (potentially having entries with no partner in the HESA list), it would be inappropriate to reference the HESA list in the documentation for the **entire** list, as opposed to just the …
=> Reference HESA field definitions in docs

lib/dfe/reference_data/degrees/types.rb, lib/dfe/reference_data/record.rb, spec/lib/dfe/reference_data/schema_validation_spec.rb, spec/support/schema_validation.rb
Fixes https://trello.com/c/V23Zyuc7/904-investigate-reference-data-deploy-to-bigquery-failure
The cause was that half of the schema validator wasn't implemented (how did nobody spot that?!?), so hadn't picked up a mistake with a schema - but BigQuery *did* pick up the problem when it tried to import the data we have into a table created with that schema.
This PR:
- Fixes the schema validator
- Adds tests for the schema validator
- Fixes the wrong schema
=> Fix schema validation (so we can import to bigquery again)

docs/schema.md, lib/dfe/reference_data/bigquery/importer.rb, lib/dfe/reference_data/degrees/grades.rb, lib/dfe/reference_data/degrees/institutions.rb, lib/dfe/reference_data/degrees/subjects.rb, lib/dfe/reference_data/degrees/types.rb, lib/dfe/reference_data/qualifications.rb, spec/lib/dfe/reference_data/schema_validation_spec.rb, spec/support/schema_validation.rb
Added the ability to declare that string fields have to match a certain regexp pattern, useful for fields that are "codes" or "IDs" rather than human readable text.
Also improved the coverage of the schema validator while I was at it, and assigned tighter schemas to the current data where appropriate.
=> Code pattern schemas

docs/lists_itt.md, lib/dfe/reference_data/itt/subjects.rb
As requested in https://trello.com/c/YgpMVHOV/936-add-more-tad-metadata-to-itt-subjects-tadcategories
...this PR adds two boolean columns to `TAD_CATEGORIES` that indicate whether they're considered STEM or EBacc subjects.
=> Added the two extra TAD category booleans

Rakefile, docs/lists_degrees.md, lib/dfe/reference_data/degrees/subjects.rb, spec/lib/dfe/reference_data/degrees/subjects_spec.rb
They're in a separate GENERIC_SUBJECTS list, with a SUBJECTS_INCLUDING_GENERICS that joins them with the standard SUBJECTS list, so services can opt-in to seeing them.
=> Added 'Not known' and 'Not applicable' generic degree subjects

Rakefile, docs/lists_degrees.md, lib/dfe/reference_data/degrees/subjects.rb, spec/lib/dfe/reference_data/degrees/subjects_spec.rb
Backport of https://github.com/DFE-Digital/dfe-reference-data/pull/71
(Making a new PR as github seemed confused about the past one and claimed the tests were failing, with an error pertaining to code not in this PR at all)
=> Generic degree subjects v1

docs/decisions/0003-special-records.md, lib/dfe/reference_data/degrees/types.rb
As per https://trello.com/c/gxLn9Utg/621-define-a-policy-for-special-reference-data-records this PR introduces an ADR suggesting a way to handle 'special' values - generic "Other" options, unknown "Not available" options, and any other categories of special values that arise in future.
It also suggests the term "special" as the encompassing thing for funny kinds of entries in lists.
Please tell me what you think!
=> Proposed ADR on special records policy

Rakefile, docs/lists_itt.md, lib/dfe/reference_data/itt/subjects.rb, spec/lib/dfe/reference_data/itt/subjects_spec.rb
This adds columns to `TAD_SUBJECTS` that map those to CAH categories (so they can, in turn, be linked through to HECoS codes for degree subjects).
We get two levels of match - direct and associated - depending on how "close" the connection is.
The data source is hand-edited data provided to me from various sources, merged together, and some common sense used to paper over the cracks.
We use a block list and an allow list, allowing a TAD subject to be associated with CAH categories at levels 1, 2 or 3 or direct to a particular degree subject ID (from `Degrees::SUBJECTS`) if we need to get really fine-grained. The block list and individual-subject-level functionality isn't used in the mappings so far, but I'm building it into the query that will consume this data so it's easy for people to …
=> CAH mappings

lib/dfe/reference_data/degrees/types.rb
[HESA has added a handful of new codes](https://github.com/DFE-Digital/dfe-reference-data/pull/82) for degree type at our request. We already have these in our reference data, so this updates with the relevant codes.
=> Add new hesa degree type codes for 2023

lib/dfe/reference_data/itt/cycles.rb, lib/dfe/reference_data/itt/incentives.rb, lib/dfe/reference_data/itt/subjects.rb
This PR includes the incentive updates required for 2024-2025 cycle. The updates were made following the details provided in the table.
As `apply_1_deadline` is not required in this cycle, it was necessary to update the schema and to make this an optional date_time field.
=> Update incentives table with 2024-2025 incentives per subject grouping

.gitignore, lib/dfe/reference_data/bigquery/importer.rb, spec/lib/dfe/reference_data/bigquery/importer_spec.rb
1. Currently if credentials are missing the importer_spec.rb raises a credentials missing error and the rest of the tests fail to run. This PR proposes a different way of handling this scenario which can be annoying if you are new to the project - instead a message is printed to the console to remind the user to add credentials for the importer spec to run and a conditional allows the rest of the tests to run
2. An update to the file path in the `importer.rb` so that the .json file can be found
3. Add .json file to .gitignore - to prevent this file being committed accidentally
=> Tidy importer_spec.rb

Rakefile, docs/lists_bank_holidays.md, lib/dfe/reference_data/bank_holidays.rb, spec/lib/dfe/reference_data/bank_holidays_spec.rb
Adding bank holidays (for England and Wales) to the gem, 2023 - 2025
Bank holidays are taken from [gov.uk](https://www.gov.uk/bank-holidays.json)
Add ability to deploy bank holidays to BigQuery
=> Add bank holidays to the gem

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
This version includes:
- Updates notes for Classical Greek studies [\#93](https://github.com/DFE-Digital/dfe-reference-data/pull/93) - a minor update
- Add bank holidays to the gem [\#92](https://github.com/DFE-Digital/dfe-reference-data/pull/92) - a non-breaking change - adds a new class to the gem which primarily will be used in Dataform for non working days query
=> v2.4.0 release

lib/dfe/reference_data/equality_and_diversity/disabilities.rb
NB. Waiting to merge in PR with new envs - causing failing tests
This PR adds 2 additional codes in the reference table to account for HESA disability codes used prior to November 2021
=> Add codes to disability hesa

Rakefile, docs/bigquery.md, docs/lists_qualifications.md, lib/dfe/reference_data/bigquery/importer.rb, spec/lib/dfe/reference_data/bigquery/importer_spec.rb
Relating to [this ticket](https://trello.com/c/9S9v8uqw/1550-define-how-we-might-configure-reference-tables-to-a-latest-version-instead-of-a-numbered-version-system) 
Reference data tables in BQ are currently suffixed with _v{release-version}
This PR updates this suffix to be _latest
The benefits - Analysts no longer need to update queries each time there is a release
N.B. some updates required in Dataform prior to merging
=> Allow BQ tables to be suffixed with _latest

CHANGELOG.md, Gemfile.lock, lib/dfe/reference_data/version.rb
- Allow BQ tables to be suffixed with _latest [\#110](https://github.com/DFE-Digital/dfe-reference-data/pull/110)
=> Release v3.5.0

lib/dfe/reference_data/itt/cycles.rb
Need to update the [dfe reference table](https://console.cloud.google.com/bigquery?project=rugged-abacus-218110&ws=!1m5!1m4!4m3!1srugged-abacus-218110!2sdfe_reference_data!3sitt_cycles_latest) for the future cycle and in this case include 2025-2026.
We need the start date of this to define the end date of the previous cycle in our reports - otherwise our reports won't update. Need to update dfe_reference_data.itt_cycles_latest
=> Add 2025-2026 cycle dates

.github/workflows/release.yml, Gemfile.lock, Rakefile, dfe-reference-data.gemspec, lib/dfe/reference_data/bigquery/converter.rb, lib/dfe/reference_data/helpers/sqlite_conversion_helper.rb, spec/lib/dfe/reference_data/bigquery/converter_spec.rb
**Trello ticket:** [here](https://trello.com/c/usmgoJWN/2156-plt-6-dfereferencedata-add-script-to-allow-reference-data-to-be-converted-to-sqlite-db?filter=member:portererica) 
**Context:** 
Currently reference data gem is a static list of hashes, access to which is provided via Ruby or by generating static mappings in JSON format. Adding a script to the rakefile which converts the reference data to sqlite db will allow other non-RoRs (i.e. .net) applications to use it.
**This PR includes:**
1. A converter module which converts each table from dfe-reference-data to sqlite
2. A converter helper module which converts values / types to be compatible with sqlite
3. An update to the release.yml to make the versioned reference data db file accessible via Github
4. An update to the Rake file, …
=> Add converter.rb and update Rakefile

lib/dfe/reference_data/itt/cycles.rb
The dates in the current release do not reflect the dates approved for 2025-26. 
This PR updates the dates to match those in the [Apply/Manage codebase](https://github.com/DFE-Digital/apply-for-teacher-training/blob/e74388f964520c0d36f44911e207e59fdf2e171a/config/initializers/cycle_timetables.rb).
=> Update 2025-26 cycle dates
